# Generate CSV

In [34]:
import pandas as pd
import numpy as np
from typing import Literal, Optional

## General Functions

In [ ]:
def concat_dfs(df1: pd.DataFrame, df2: pd.DataFrame) -> pd.DataFrame:
    return pd.concat([df1, df2], ignore_index=True)

def create_csv(df:pd.DataFrame, filename: str) -> None:
    df.to_csv(filename, index=False)

## meters.csv

In [86]:
def create_meters_df() -> pd.DataFrame:
    return pd.DataFrame(columns=[
        "meter_id",
        "meter_name",
        "user_id",
        "location",
        "direction"
    ])

def add_meter(
    df: pd.DataFrame,
    meter_id: str,
    user_id: str,
    direction: Literal["consumption", "generation"],
    location: str,
    meter_name: Optional[str] = None
) -> pd.DataFrame:
    
    new_row = pd.DataFrame([{
        "meter_id": meter_id,
        "meter_name": meter_name,
        "user_id": user_id,
        "location": location,
        "direction": direction 
    }])

    return concat_dfs(df, new_row)

def generate_meters_csv() -> pd.DataFrame:
    meters_df = create_meters_df()
    meters_df = add_meter(meters_df, "mp_1", "Manfred", "Vienna", "consumption")
    meters_df = add_meter(meters_df, "mp_2", "Manfred", "Vienna", "consumption")

    create_csv(meters_df, "meters.csv")

    return meters_df

meters_df = generate_meters_csv()

meters_df

  meter_id meter_name  user_id     location direction
0     mp_1       None  Manfred  consumption    Vienna
1     mp_2       None  Manfred  consumption    Vienna

## timeseries.csv

In [79]:
def create_timeseries_df() -> pd.DataFrame:
    return pd.DataFrame(columns=[
        "meter_id",
        "timestamp",
        "value",
        "unit"
    ])

def add_timeseries(
    df: pd.DataFrame,
    meter_id: str,
    timestamps: list,
    values: list[float],
):
    new_timeseries = pd.DataFrame({
        "meter_id": meter_id,
        "timestamp": timestamps,
        "vlaues": values,
        "unit": "kWh"
    })

    return concat_dfs(df, new_timeseries)

In [80]:
ts_df = create_timeseries_df()

# ts_df = add_timeseries(ts_df, ...)

ts_df

Empty DataFrame
Columns: [meter_id, timestamp, value, unit]
Index: []